spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teamf?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: whgdms1984!

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug